# services:
#   - docker
before_install:
  - echo "before install"
  - echo "hello multus" > multus
  - ls -lth

install:
  - echo "need install"

deploy:
  provider: releases
  api_key:
    secure: EGRcnen0aIfXq1mEZLLJ1gZwgTWALtGRhceJVPk/4yYllzsNC/67vUz5Hfw+Rs+0py7H6m4vF6Z0VS9hlrH/D6pAr/Gdq3Jramn6UBySPMowGjGLlT6Tr2YT8wyZQX6EeNRVwYM7xJZnZnkP2AN1m8YIG8UC4mAH8jRLuLZjLqtmdi78wrB3/j/doMUkMhBL6M8UQpjl8PMhrbnTB+2rzQfk6R0V+7ulGwYyQaEkjQRzAxSQ4CjSGp9nmSGGaruscgRtFTKxeIqAKcvuBF9DJWBY7GoebElSkiWJ6PF9byF+BPqbupNciyjwpkySbu8a7hWDGkdJtrDd55JCbuOzAmI2phojC13JiOCve4CoIYcDIe7kBdrbNFdv4S2J8ckLsLdsB5UMKIyuYCJNbVlBxo4emxLUQWyyQQ1JlImWhNVDoEB50HpqmNfJg0pb/wzI4YN9xVohkDCOvQiPvjdP+BdtfqNvgplBDxz+6wPuEXShPkCARUMQy1xMAMXJz9t16j0okxqpp1ufdZsX3wndXl4pgSyYri9+d5NcO7nCzeyYfEOI7XGo7S1b7ExqAWA0A/dAqzObJpCj3Z3+PufvW/QLF17VqXlHfqI0ThsDkQ/qeG2uJuReGNslluJbGvH9GZF/dJ3HYCbcTbgSfvwLCpebLN5LyK9MZEmXGRmZ0Gs=
  file: multus
  on:
    repo: wxdlong/multus
