services:
  - docker

before_install:
  - echo "before install"
  - echo "hello multus" > multus
  - ls -lth
  
deploy:
  provider: releases
  api_key:
    secure: "tgPHFokGAQD/VqbETEl1hh2vGFACT9hxAv9BZ4yP7WPlIgm9t0/SE85SK99ojAh30y4/Vc+st47pI1xKXGYYhVZPFe75z7PKTCC5g3+U41KgydC8LPdaQoAlVYKNXbvxaKw4VQ0twe/3wweUw9TdYHw3krMEHsqDhBPeeqJI6zSkZsv9FX7tJLNQdnDRzYXxoIiuU3IB2m652xsuhMI29ilXjqD8+YVBjEkhrvO5UrWLpkXOf8wAH+EOgRshctu2pMcXEEDbGsVRofO84fOdgNpGSdmkS8rseSQEWGA/x1pcvNv2cvu6rQihPB5yJH14YYlvvICg7YnhqGqSsXk1pg8SNeidzdxSBkOj533e86WBA8X9A704PdvEfMzuEc/SJ0j2XP37qHkPGvMAPnpwk/81TA7GaAmItEVORyl3j0pcLFgweWD34imt9mnteOs0vkHEiWgr7+NHburWka+VsNhu7gzub4Enc1yvcSsJdJ5tk91lfF4TxraExdXPB1uLxR+Poo3BLjbl6p8InZIEI/oas/kz9yeVCJPYz7dgxfK9jHwqfAo8XlkS7WIq/k2M4ydL2ljG98W1ziL0Yze39ONv1beushESl11nj7vsD74vwZxKy4ViEjRTEuQTxo8CMCn5niZB516K8iGcHFwXVdkPjMdDWX3eXyMqHvJYDzU="
  file: "multus"
  skip_cleanup: true
  on:
    tags: true